Project_DiseaseInfoAPI/DiseaseInfoAPI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('api/', include('api.urls')),
    path('rest-auth/', include('rest_auth.urls')),
    path('rest-auth/registration/', include('rest_auth.registration.urls')),
    path('', include('chatbot.urls')),
]

Project_DiseaseInfoAPI/api/urls.py
from django.urls import path
from . import views
from rest_framework_jwt.views import obtain_jwt_token, verify_jwt_token, refresh_jwt_token

app_name = 'api'

urlpatterns = [
    path('token/', obtain_jwt_token, name='generate'),
    path('token/verify/', verify_jwt_token, name='verify'),
    path('token/refresh/', refresh_jwt_token, name='refresh'),
    path('data/', views.data, name='data'),
    path('data/<int:pk_id>/', views.choose, name='choose'),
]

Project_DiseaseInfoAPI/chatbot/urls.py
from django.urls import path
from . import views
from decouple import config
base = "https://api.telegram.org"
token = config('TOKEN')

app_name = 'chatbot'

urlpatterns = [
    path('<str:telegram_token>', views.webhook, name='webhook'),
]

Project_DiseaseInfoAPI/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('tables', views.tables, name='tables'),
]

Project_DiseaseInfoAPI/api/models.py
from django.db import models

class Disease(models.Model):
    name = models.CharField(max_length=30)
    symptom = models.TextField()
    diagnosis = models.TextField()

Project_DiseaseInfoAPI/chatbot/models.py
from django.db import models

# Create your models here.

Project_DiseaseInfoAPI/main/models.py
from django.db import models

Project_DiseaseInfoAPI/api/views.py
from django.shortcuts import render
from .models import Disease
from django.core import serializers
from django.http import HttpResponse
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication

@api_view(['GET'])
@permission_classes((IsAuthenticated,))
@authentication_classes((JSONWebTokenAuthentication,))
def data(request):
    diseases = Disease.objects.all()
    serializer = serializers.serialize('json', diseases)
    return HttpResponse(serializer, content_type='text/json-comment-filtered')

@api_view(['GET'])
@permission_classes((IsAuthenticated,))
@authentication_classes((JSONWebTokenAuthentication,))
def choose(request, pk_id):
    diseases = Disease.objects.filter(pk=pk_id)
    serializer = serializers.serialize('json', diseases)
    return HttpResponse(serializer, content_type='text/json-comment-filtered')

Project_DiseaseInfoAPI/chatbot/views.py
from django.shortcuts import render, redirect, get_object_or_404
from telegram.ext import Updater, MessageHandler, Filters
from django.http import StreamingHttpResponse, HttpResponse
from decouple import config
import requests
from pprint import pprint as pp
from django.views.decorators.http import require_POST
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
from api.models import Disease

base = "https://api.telegram.org"
token = config('TOKEN')
chat_id = config('CHATID')


@csrf_exempt
def webhook(request, telegram_token):
    url = f'{base}/bot{telegram_token}/setWebhook?url=https://diseaseinfoapi.herokuapp.com/{telegram_token}'
    requests.get(url).json()
    body = request.body
    body = body.decode('utf-8')
    res = json.loads(body)

    if res.get('message'):
        text = res.get('message').get('text')
        username = res.get('message').get('from').get('last_name') + res.get('message').get('from').get('first_name')
        method = 'sendMessage'
        if Disease.objects.filter(name=text).exists():
            index = Disease.objects.get(name=text).pk
            data = {
                'username': username,
                'password': 'qlalfqjsgh',
            }
            res = requests.post(config('URL_GENERATE'), data=data).json()
            headers = {
                'Authorization': 'jwt ' + res.get('token'),
            }
            url_data = config('URL_DATA')
            getData = requests.get(f'{url_data}/{index}/', headers=headers).json()
            text = '[증상] : ' + getData[0].get('fields').get('symptom') + '\n\n[진단] : ' + getData[0].get('fields').get('diagnosis')
        else:
            db = '[ '
            for value in Disease.objects.all():
                db += value.name + ' '
            db += ' ]'
            text = f'해당 키워드에 일치하는 정보가 없습니다. \n{db}'
        url = f'{base}/bot{token}/{method}?chat_id={chat_id}&text={text}'
        requests.get(url)
    return HttpResponse(f'/{telegram_token}')

Project_DiseaseInfoAPI/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from api.models import Disease
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from rest_framework.permissions import IsAuthenticated
from rest_framework_jwt.authentication import JSONWebTokenAuthentication
from django.contrib.sessions.models import Session

def index(request):
    return render(request, 'main/index.html')
    
def register(request):
    return render(request, 'main/register.html')

def login(request):
    return render(request, 'main/login.html')
    
def tables(request):
    diseases = Disease.objects.all()
    return render(request, 'main/tables.html', {'diseases':diseases})

Project_DiseaseInfoAPI/chatbot/templates/chatbot/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="/send">
        <input type="text" name="msg">
        <button>Send</button>
</body>
</html>

Project_DiseaseInfoAPI/main/templates/main/_content.html
{% load static %}
<div class="container-fluid">
    <!-- REST API Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">REST-API</h6>
        </div>
        <div class="card-body" style="margin: 0% 10%;">
            <div class="input-group mt-3 mb-3">
                <div class="input-group-prepend">
                </div>
                <div class="input-group-append">
                    <button class="btn btn-primary" id="reqGenerate" style="width: 120px;">토큰 값</button>
                </div>
                <input type="text" class="form-control" id="getToken" placeholder="로그인 해주세요. 토큰값이 필요합니다.">
            </div>
            <hr>
            <div class="input-group mt-3 mb-3">
                <div class="input-group-prepend">
                </div>
                <div class="input-group-append">
                    <button class="btn btn-primary" id="reqVerify" style="width: 120px;">토큰 검증</button>
                </div>
                <input type="text" class="form-control" id="resVerify" placeholder="생성된 토큰의 검증 결과입니다." readonly>
            </div>
            <hr>
            <div class="input-group mt-3 mb-3">
                <div class="input-group-prepend">
                </div>
                <div class="input-group-append">
                    <button class="btn btn-primary" id="reqRefresh" style="width: 120px;">토큰 갱신</button>
                </div>
                <input type="text" class="form-control" id="getRetoken" placeholder="갱신된 토큰값입니다." readonly>
            </div>
            <hr>
            <div class="input-group mt-3 mb-3">
                <div class="input-group-prepend">
                </div>
                <div class="input-group-append">
                    <button class="btn btn-primary" id="reqData" style="width: 120px;">데이터 요청</button>
                </div>
                <input type="text" class="form-control" id="resData" placeholder="데이터 요청 결과입니다." readonly>
            </div>
        </div>
    </div>

    <!-- Collapsable Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Accordion -->
        <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button"
            aria-expanded="true" aria-controls="collapseCardExample">
            <h6 class="m-0 font-weight-bold text-primary">Response Result</h6>
        </a>
        <!-- Card Content - Collapse -->
        <div class="collapse collapse" id="collapseCardExample">
            {% include 'main/_contentTable.html' %}
        </div>
    </div>

</div>
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
<script>
    $('#getToken').val(sessionStorage.getItem('token'));
</script>
<script src="{% static 'main/js/reqAjax.js' %}"></script>
{% endblock %} 

Project_DiseaseInfoAPI/main/templates/main/_contentTable.html
{% block css %}
<style>
.th > .th-1 {
    width: 5%;
}
.th > .th-2 {
    width: 10%;
}
.th > .th-3 {
    width: 35%;
}
.th > .th-4 {
    width: 50%;
}
</style>
{% endblock %}
<!-- DataTales Example -->
<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered" width="100%" cellspacing="0">
            <thead class="bg-gray-400">
                <tr class="th">
                    <th class="th-1">No</th>
                    <th class="th-2">병명</th>
                    <th class="th-3">증상</th>
                    <th class="th-4">진단 결과</th>
                </tr>
            </thead>
            <tbody id="dataTable">
            </tbody>
        </table>
    </div>
</div>

Project_DiseaseInfoAPI/main/templates/main/_footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; DiseaseInfo REST-API 2019</span>
        </div>
    </div>
</footer>

Project_DiseaseInfoAPI/main/templates/main/_sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'main:index' %}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">오 인 용<sup></sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'main:index' %}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
      Interface
  </div>
  {% if user.is_authenticated %}
  <!-- Nav Item - Logout -->
  <li class="nav-item">
    <a class="nav-link" href="" id="logout">
      <i class="fas fa-fw fa-sign-out-alt"></i>
      <span>Logout</span></a>
  </li>
  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'main:tables' %}">
      <i class="fas fa-fw fa-table"></i>
      <span>Data Tables</span></a>
  </li>
  {% else %}
  <!-- Nav Item - Login -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'main:login' %}">
      <i class="fas fa-fw fa-sign-in-alt"></i>
      <span>Login</span></a>
  </li>

  <!-- Nav Item - Register -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'main:register' %}">
      <i class="fas fa-fw fa-user"></i>
      <span>Register</span></a>
  </li>
  {% endif %}

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

Project_DiseaseInfoAPI/main/templates/main/_tableData.html
{% block css %}
<style>
.th > .th-1 {
    width: 5%;
}
.th > .th-2 {
    width: 10%;
}
.th > .th-3 {
    width: 35%;
}
.th > .th-4 {
    width: 50%;
}
</style>
{% endblock %}
<div class="container-fluid">
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Disease DataTables</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr class="th">
                            <th class="th-1">No</th>
                            <th class="th-2">병명</th>
                            <th class="th-3">증상</th>
                            <th class="th-4">진단</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for disease in diseases %}
                        <tr>
                            <td>{{ disease.pk }}</td>
                            <td>{{ disease.name }}</td>
                            <td>{{ disease.symptom }}</td>
                            <td>{{ disease.diagnosis }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

Project_DiseaseInfoAPI/main/templates/main/_topbar.html
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

    <!-- Page Heading -->
    {% if request.resolver_match.url_name == 'tables' %}
    <h1 class="display-5">Tables</h1>
    {% elif request.resolver_match.url_name == 'charts' %}
    <h1 class="display-5">Charts</h1>
    {% else %}
    <h1 class="display-5">Dashboard</h1>
    {% endif %}
    
</nav>

Project_DiseaseInfoAPI/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>DiseaseInfo</title>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'main/favicon/favicon-16x16.png' %}">
    <!-- Custom fonts for this template-->
    <link href="{% static 'main/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'main/css/sb-admin-2.min.css' %}" rel="stylesheet">
    {% block css %}
    {% endblock %}
</head>
<body id="page-top" class="bg-gradient-primary">
    {% block body %}
    {% endblock %}
    
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'main/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'main/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    
    <!-- Core plugin JavaScript-->
    <script src="{% static 'main/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    
    <!-- Custom scripts for all pages-->
    <script src="{% static 'main/js/sb-admin-2.min.js' %}"></script>
    
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>
    <script>
        const csrftoken = Cookies.get('csrftoken');
    </script>
    <script src="{% static 'main/js/user.js' %}"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

Project_DiseaseInfoAPI/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block body %}
<!-- Page Wrapper -->
<div id="wrapper">
  <!-- Sidebar -->
  {% include 'main/_sidebar.html' %}
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
      <!-- Topbar -->
      {% include 'main/_topbar.html' %}
      <!-- End of Topbar -->

      <!-- Begin Page Content -->
      {% include 'main/_content.html' %}
      <!-- /.container-fluid -->
    </div>
    <!-- End of Main Content -->

    <!-- Footer -->
    {% include 'main/_footer.html' %}
    <!-- End of Footer -->
  </div>
  <!-- End of Content Wrapper -->
</div>
<!-- End of Page Wrapper -->

{% endblock %}

Project_DiseaseInfoAPI/main/templates/main/login.html
{% extends 'main/base.html' %}
{% load static %}
{% block body %}
<div class="container">

  <!-- Outer Row -->
  <div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                </div>
                <form class="user" onsubmit="return false;">
                  <div class="form-group">
                    <input type="text" class="form-control form-control-user" id="loginUsername"
                      aria-describedby="emailHelp" placeholder="Enter User Id">
                  </div>
                  <div class="form-group">
                    <input type="password" class="form-control form-control-user" id="loginPassword"
                      placeholder="Password">
                  </div>
                  <div class="form-group">
                    <div class="custom-control custom-checkbox small">
                      <input type="checkbox" class="custom-control-input" id="customCheck">
                      <label class="custom-control-label" for="customCheck">Remember Me</label>
                    </div>
                  </div>
                  <button class="btn btn-primary btn-user btn-block" id="login">Login</button>
                  <hr>
                  <a href="{% url 'main:register' %}" class="btn btn-success btn-user btn-block">
                    <i class="fa fa-user fa-fw"></i> Create an Account!
                  </a>
                  <a href="{% url 'main:index' %}" class="btn btn-facebook btn-user btn-block">
                    <i class="fa fa-home fa-fw"></i> Go Home?
                  </a>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>
{% endblock %}

Project_DiseaseInfoAPI/main/templates/main/register.html
{% extends 'main/base.html' %}
{% block body %}
<div class="container">

  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
            </div>
            <form class="user" onsubmit="return false;">
              <div class="form-group">
                <input type="text" class="form-control form-control-user" id="registerUsername"
                  placeholder="UserId">
              </div>
              <div class="form-group row">
                <div class="col-sm-6 mb-3 mb-sm-0">
                  <input type="password" class="form-control form-control-user" id="registerPassword"
                    placeholder="Password">
                </div>
                <div class="col-sm-6">
                  <input type="password" class="form-control form-control-user" id="repeatPassword"
                    placeholder="Repeat Password">
                </div>
              </div>
              <button class="btn btn-primary btn-user btn-block" id="register">Register Account</button>
              <hr>
              <a href="{% url 'main:login' %}" class="btn btn-success btn-user btn-block">
                <i class="fa fa-sign-in-alt fa-fw"></i> Already have an account? Login!
              </a>
              <a href="{% url 'main:index' %}" class="btn btn-facebook btn-user btn-block">
                <i class="fa fa-home fa-fw"></i> Go Home?
              </a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
{% endblock %}

Project_DiseaseInfoAPI/main/templates/main/tables.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
  <!-- Custom styles for this template-->
  <link href="{% static 'main/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block body %}
  <!-- Page Wrapper -->
  <div id="wrapper">
    <!-- Sidebar -->
    {% include 'main/_sidebar.html' %}
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        {% include 'main/_topbar.html' %}
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        {% include 'main/_tableData.html' %}
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      {% include 'main/_footer.html' %}
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  {% block scripts %}
    <!-- Page level plugins -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'main/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'main/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
    
    <!-- Page level custom scripts -->
    <script src="{% static 'main/js/demo/datatables-demo.js' %}"></script>
  {% endblock %}

{% endblock %}